language: python
sudo: enabled
python: 3.6
install:
  -pip install -r requirements.txt
  -pip install coverage
script:
  -pytest
  -coverage run --source=app -m pytest && coverage report

after_success:
  -coveralls
after_success:
  coveralls
