language:
  - python

# python versions supported
python:
  - 3.5

# install dependencies
install:
  - pip install -r requirements.txt


script:
  # run tests with coverage
  -  pytest 

after_success:
  # coverage report
  - coveralls