language: python
sudo: enabled
python:
  - 3.6
before_script:
  - easy_install distribute
  - pip install -r requirements.txtt

script:
  -pytest
  -coverage run --source=app -m pytest 

after_success:
  -coveralls
after_success:
  coveralls
